### ISSUE TITLE
Email template not responsive, take a look at screenshot, it's email at my phone

### ISSUE THREAD

**Issue by khlystov** [mailgun/transactional-email-templates#3] opened 2014-10-15 11:02 UTC
![emailtemplate](https://cloud.githubusercontent.com/assets/1534096/4644415/c80e8eec-545a-11e4-8b52-367a7fb0db0b.jpg)

**Comment by leemunroe** [comment] 2015-02-10 22:33
@khlystov Did you happen to find a solution for Gmail on Android?

**Comment by leemunroe** [comment] 2015-04-22 21:58
Closing to clean up. Couldn't reproduce.

**Closed by leemunroe** 2015-04-22 21:58 UTC
