### ISSUE TITLE
outlook.com doesn't center the body

### ISSUE THREAD

**Issue by naczu** [mailgun/transactional-email-templates#18] opened 2015-08-05 08:41 UTC
Hi. these email temps are very useful. But outlook.com doesn't center billing.html body

**Comment by acorncom** [comment] 2015-09-08 21:22
See Issue #11 ?

**Comment by naczu** [comment] 2015-09-09 12:25
no it is not about outlook 2007. it is about outlook.com. first outlook.com doesn't center the body of the page. I think issue is about css ecxcontainer class. And "alert alert-warning" class doesn't work. There are problems for outlook.com 
<img width="1272" alt="screenshot" src="https://cloud.githubusercontent.com/assets/3453734/9761660/da1dfb18-5706-11e5-83fb-4fc93303b503.png">

**Comment by leemunroe** [comment] 2015-09-10 03:33
If you change the `margin` on the container `<td>` to `Margin`, with a capital "M", that will fix the centering issue i.e. `Margin: 0 auto;` 

I'll update the repo shortly.

**Comment by leemunroe** [comment] 2015-09-10 03:35
@naczu I wasn't able to reproduce the alert banner issue. Not with Litmus any way. Mind sharing the exact HTML you're sending?

![image](https://cloud.githubusercontent.com/assets/15963/9779605/402542e2-5732-11e5-9128-04b4abbb32b2.png)

**Comment by naczu** [comment] 2015-09-10 16:10
I use email alert http://mailgun.github.io/transactional-email-templates/alert.html. I think outlook made something new for filtering css files. I don't know what is wrong.

**Comment by leemunroe** [comment] 2015-09-10 18:35
Ah yes you need to inline the styles before sending it out.

[Mentioned here](https://github.com/mailgun/transactional-email-templates#how-to-use) but sorry if I didn't make it clear.

**Comment by lembitk** [comment] 2016-02-14 22:19
As Lee said, to center the main container `<td>`, the "M" in its CSS property name [`Margin` has to be capitalized](https://www.emailonacid.com/blog/article/email-development/outlook.com-does-support-margins/). 

I tested all three templates in Outlook.com, and in addition to the `<td class="container">` shared by all of them, there are 3 other HTML elements in 'billing.html' (a `<h1>` heading, a `<h2>` heading, `<table class="invoice">`) which need `Margin` for improved display. Comparisons below. 

<img src="https://cloud.githubusercontent.com/assets/1476817/13036520/3112a864-d372-11e5-9f4c-0fe0fffa9fb3.png" width="45%" align="left"><img src="https://cloud.githubusercontent.com/assets/1476817/13036521/329efbf6-d372-11e5-91ff-400917a2f925.png" width="45%">
<img src="https://cloud.githubusercontent.com/assets/1476817/13036522/33c24a4c-d372-11e5-94ba-e15d7e357939.png" width="45%" align="left"><img src="https://cloud.githubusercontent.com/assets/1476817/13036689/b069965a-d376-11e5-9933-941cd9a974bd.png" width="45%">

As this "hack" is ridiculously simple, it's also super easy to overlook – and rather inconvenient to deal with in regards to inlined CSS we need in final emails. Namely, CSS inliners will uncapitalize `margin`, so writing `Margin` in 'styles.css' is mere documenting, and to actually apply it, it has to be capitalized by hand in final emails (the HTML code with inlined CSS).

With that said, as it's a useful addition IMHO, I will open a PR with this fix documented for 3 CSS rules in 'styles.css', and applied to corresponding HTML elements in 'inlined/action.html', 'inlined/alert.html', 'inlined/billing.html'.

**Comment by TedGoas** [comment] 2016-03-03 22:21
Is this an issue anymore since Outlook.com has been replaced by Outlook365 (which doesn't suffer from this bug)?

**Comment by lembitk** [comment] 2016-03-04 19:29
Thanks @TedGoas. While at the moment my Outlook.com hasn't upgraded yet, [Microsoft writes that everyone should get the new version soon](https://blogs.office.com/2016/02/17/outlook-com-out-of-preview-and-better-than-ever/) (“we’re rolling out these upgrades to Outlook.com users as quickly as possible, with millions of accounts being upgraded each week”).

It's great news if we can start to forget about many rendering quirks of Outlook.com, including this issue. And while I personally would like to re-test this after getting access to Office 365-based Outlook.com, I'm sure repo's owners would be happy to close this issue (along with #21) sometime soon.

**Closed** 2017-04-25 12:18 UTC
